game.resources = [
	{name: "sheet", type:"image", src: "data/map/sheet.png"},
	{name: "metatiles32x32", type:"image", src: "data/map/metatiles32x32.png"},
	{name: "background", type:"image", src: "data/map/background.png"},
	{name: "superscore", type:"image", src: "data/map/score.png"},
	{name: "score", type:"image", src: "data/map/normalscore_32x32.png"},
	{name: "pacman", type:"image", src:"data/img/pacman_sheet.png"},
	{name: "pinky", type:"image", src:"data/img/pinky/pinky_sheet.png"},
	{name: "clyde", type:"image", src:"data/img/clyde/clyde_sheet.png"},
	{name: "inky", type:"image", src:"data/img/inky/inky_sheet.png"},
	{name: "blinky", type:"image", src:"data/img/blinky/blinky_sheet.png"},
	{name: "halftrans", type:"image", src:"data/img/halftrans.png"},
	{name: "cherry_32", type:"image", src:"data/img/cherry_32.png"},
	{name: "title", type:"image", src:"data/img/title.png"},
	{name: "arrowleft", type:"image", src:"data/img/arrow_left.png"},
	{name: "arrowright", type:"image", src:"data/img/arrow_right.png"},
	{name: "arrowdown", type:"image", src:"data/img/arrow_down.png"},
	{name: "arrowup", type:"image", src:"data/img/arrow_up.png"},
	{name: "level", type: "tmx", src: "data/map/level.tmx"},
	{name: "32x32_font", type:"image", src: "data/font/32x32_font.png"}	 
];
